name: common_utils
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/rational
  rational: ^2.2.3
  # https://pub.dev/packages/decimal
  decimal: ^3.2.1
  # https://pub.dev/packages/crypto
  crypto: ^3.0.6
  # https://pub.dev/packages/convert
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0